apiVersion: v1
kind: Service
metadata: # kpt-merge: old/the-service
  name: the-service
  namespace: old
  annotations:
    internal.kpt.dev/upstream-identifier: "|Service|old|the-service"
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: # kpt-merge: /the-crd
  name: the-crd
  annotations:
    internal.kpt.dev/upstream-identifier: apiextensions.k8s.io|CustomResourceDefinition|default|the-crd
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: crd-svc
          namespace: old
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata: # kpt-merge: /the-api-service
  name: the-api-service
  annotations:
    internal.kpt.dev/upstream-identifier: apiregistration.k8s.io|APIService|default|the-api-service
spec:
  service:
    name: api-svc
    namespace: old
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /crb1
  name: crb1
  annotations:
    internal.kpt.dev/upstream-identifier: rbac.authorization.k8s.io|ClusterRoleBinding|default|crb1
subjects:
  - kind: ServiceAccount
    name: default
    namespace: old
